#-------------------------------
# Site Settings
title: Penelop Anthias
description: Associate Professor
color_scheme: light # You have the option to choose between three modes: auto, light, and dark. The default mode is set to auto, which means that the color scheme will automatically adapt based on your operating system settings. This way, you can enjoy a personalized experience without having to manually switch between light and dark modes.


#-------------------------------
# Global Cover
global_cover:
  enable: true
  homepage_image: "/client_images/homebanner.jpg" # This line allows you to add a beautiful image at the top of your site, creating an eye-catching visual element that enhances the overall appearance and appeal.


#-------------------------------
# Breadcrumbs
breadcrumbs:
  enable: true # This line of code enables you to easily incorporate breadcrumbs into your website. By setting the "enable" parameter to "true", breadcrumbs will be enabled on your website, allowing users to easily track their navigation and find relevant information. Conversely, setting the parameter to "false" will disable the display of breadcrumbs, removing this navigation feature from your website.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Research'
      url: '/research/'
    - title: 'Publications'
      url: '/publications/'
    # - title: '🚀 Projects'
    #   url: '/projects/'
    - title: 'Films'
      url: '/videos/'
    # - title: '👨🏻‍💻 About'
    #   url: '/about/'
    # - title: '📷 Gallery'
    #   url: '/gallery/'
    # - title: '✍️ Blog'
    #   url: '/blog/'
    # - title: '📔 Elements'
    #   url: '/elements/'
    - title: 'Updates'
      url: '/updates/'
    - title: 'Teaching'
      url: '/teaching/'
    - title: 'Impact'
      url: '/impact/'
    - title: 'Books'
      url: '/books/'


#-------------------------------
# Author Settings
author:
  author_name: Dr. Penelop Anthias
  author_role: Associate Professor
  author_bio: My research examines struggles around indigeneity, territory and the politics of resource extraction in Latin America. This work is grounded in a decade and a half of engaged ethnographic research in Bolivia’s Chaco region.
  author_avatar: '/images/profile_picture.jpg'
  cta_button_text: Contact Me
  cta_button_link: '/contact/'



#-------------------------------
# Settings
updates:
  enable: true
  updates_title: "Latest Updates"
  updates_page_url: "/updates"
  updates_description: "Stay informed with the latest events and announcements. Check back monthly for updates."

update_items:
  - date: "2024-09-01"
    content: "[Update your latest update]"
  - date: "2024-08-20"
    content: "[Update your latest update]"
  - date: "2024-08-15"
    content: "[Update your latest update]"

research:
  enable: true
  research_title: "My Research"
  research_description: 


publication:
  enable: true
  publication_title: "Books" # Change or leave it empty if you want the title to be set elsewhere
  publication_description: # You can modify this description as needed
  publication_page_url: "/publications" # The URL where all publications are listed
  publication_image_url: "/images/book.png" # The image URL for the book or publication
  publication_author: # The name of the author
  publication_content: "Winner of the 2019 Best Book in Race, Ethnicity and Comparative Politics, American Political Science Association Section on Race, Ethnicity and Politics. Investigates the persistent struggles of Guaraní communities in Bolivia as they strive for land and autonomy. Based on ethnographic research, it reveals how their efforts to map and claim territory have been obstructed by governmental boundaries, resistance from landowners, and hydrocarbon projects.   <a href='https://www.cornellpress.cornell.edu/book/9781501714368/limits-to-decolonization/#bookTabs=1'><b>Get it today</b></a>."

#-------------------------------
# Projects Settings
projects_settings:
  enable: false
  projects_title: Portfolio
  projects_description:


#-------------------------------
# about settings
about_settings:
  enable: true
  about_title: "About Dr. Penelope Anthias"
  about_description: "Dr. Penelope Anthias is an Associate Professor of Geography at Durham University. Her research focuses on the intersection of indigeneity, territory, and resource extraction in Latin America, particularly Bolivia. With over 15 years of ethnographic research, she combines anti-colonial, Marxist, and Foucaultian theories with participatory methods. Her acclaimed book, *Limits to Decolonization*, explores Bolivia’s Native Community Lands (TCOs) and she actively mentors PhD students in postcolonial geographies and land politics."



#-------------------------------
# Testimonials Settings
testimonials:
  enable: false
  testimonials_title: Testimonials
  testimonials_description:

testimonial_items:
  - name: "Albert Flores"
    image: "/images/client-1.jpg"
    designation: "Data Scientist"
    content : "The incredible attention to detail displayed by this team is commendable. Every aspect of our project, no matter how small, was handled with precision and care. The result is a product that reflects their commitment to excellence."

  - name: "Wade Warren"
    image: "/images/client-2.jpg"
    designation: "DevOps Engineer"
    content : "Working with this creative powerhouse was an enlightening experience. Their brilliance in design thinking and creative solutions brought our project to life in ways we hadn't imagined. The team's passion for innovation is truly infectious."

  - name: "Jenny Wilson"
    image: "/images/client-3.jpg"
    designation: "Systems Analyst"
    content : "This team proved to be efficient problem solvers throughout our project. When faced with challenges, they tackled them with creativity and resourcefulness. Their ability to overcome obstacles ensured a smooth and successful project delivery."


#-------------------------------
# Blog Section
blog_settings:
  enable: false
  blog_title: Writing
  blog_description:


#-------------------------------
# Videos Settings
videos_settings:
  enable: true
  videos_title: Films
  videos_description:


#-------------------------------
# Gallery Section
gallery_settings:
  enable: false
  gallery_title: Gallery
  gallery_description:

articles:
  enable: true
  articles_title: "Latest Publication"
  articles_description: "Explore my latest publications on a variety of topics."

#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: true
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_title: Get interesting news
  mailchimp_description: Subscribe to our newsletter and we’ll send you the emails of latest posts.
  mailchimp_input_text: Your email address...
  mailchimp_button_text: Join Me # Add your button text


#-------------------------------
# Social Icons Settings
social:
- {icon: "fa-brands fa-facebook", name: "Facebook", link: "https://www.facebook.com/profile.php?id=100090929704323"}
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://x.com/PenelopeAnthias"}
# - {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com"}
# - {icon: "fa-brands fa-tiktok", name: "Tiktok", link: "https://tiktok.com"}
- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://www.youtube.com/@penelopeanthias"}
# - {icon: "fa-brands fa-pinterest", name: "Pinterest", link: "https://pinterest.com"}
# - {icon: "fa-brands fa-dribbble", name: "Dribbble", link: "https://dribbble.com"}
# - {icon: "fa-brands fa-microsoft", name: "Microsoft", link: "https://microsoft.com"}
# - {icon: "fa-brands fa-vimeo-v", name: "Vimeo", link: "https://vimeo.com"}
- {icon: "fa-solid fa-envelope", name: "Email", link: "mailto:penelope.f.anthias@durham.ac.uk"}
- {icon: "fa-solid fa-globe", name: "Website", link: "https://www.durham.ac.uk/staff/penelope-f-anthias/"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-dribbble", name: "Dribbble" link: "https://dribbble.com"}
# Other icons can be found at https://fontawesome.com/search?o=r&m=free


#-------------------------------
# Contact Settings
contact:
  email: mjkbdaor # Add your form_id
  description: Thank you for visiting my website. If you would like to discuss research collaborations, PhD supervision, or have inquiries about my work on Indigenous land rights, resource politics, or other related topics, please feel free to get in touch by filling out the form below. I look forward to connecting with you.

# NOTE
# Priam theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id